// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoProject.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    partial class CrmDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lead", b =>
                {
                    b.Property<int>("LeadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeadID"));

                    b.Property<int>("AssignedRepId")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeadID");

                    b.HasIndex("AssignedRepId");

                    b.ToTable("Leads");

                    b.HasData(
                        new
                        {
                            LeadID = 1,
                            AssignedRepId = 1,
                            Company = "Infosys",
                            CreatedDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rahul Sharma",
                            PhoneNo = "9999999999",
                            Position = "Manager",
                            Priority = "High",
                            Source = "Website",
                            Status = "New"
                        },
                        new
                        {
                            LeadID = 2,
                            AssignedRepId = 2,
                            Company = "TCS",
                            CreatedDate = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Priya Verma",
                            PhoneNo = "8888888888",
                            Position = "Director",
                            Priority = "Medium",
                            Source = "Referral",
                            Status = "Contacted"
                        });
                });

            modelBuilder.Entity("LeadInteraction", b =>
                {
                    b.Property<int>("InteractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteractionId"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FollowUpDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("InteractionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InteractionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeadId")
                        .HasColumnType("int");

                    b.HasKey("InteractionId");

                    b.HasIndex("LeadId");

                    b.ToTable("LeadInteractions");

                    b.HasData(
                        new
                        {
                            InteractionId = 1,
                            Details = "Initial discussion completed",
                            FollowUpDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InteractionDate = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InteractionType = "Call",
                            LeadId = 1
                        },
                        new
                        {
                            InteractionId = 2,
                            Details = "Proposal shared",
                            FollowUpDate = new DateTime(2024, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InteractionDate = new DateTime(2024, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InteractionType = "Email",
                            LeadId = 2
                        });
                });

            modelBuilder.Entity("SalesRepresentative", b =>
                {
                    b.Property<int>("RepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RepId");

                    b.ToTable("SalesRepresentatives");

                    b.HasData(
                        new
                        {
                            RepId = 1,
                            Department = "Sales",
                            Email = "nikhil@gmail.com",
                            Name = "Nikhil"
                        },
                        new
                        {
                            RepId = 2,
                            Department = "Sales",
                            Email = "amit@gmail.com",
                            Name = "Amit"
                        });
                });

            modelBuilder.Entity("Lead", b =>
                {
                    b.HasOne("SalesRepresentative", "SalesRepresentative")
                        .WithMany("Leads")
                        .HasForeignKey("AssignedRepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesRepresentative");
                });

            modelBuilder.Entity("LeadInteraction", b =>
                {
                    b.HasOne("Lead", "Lead")
                        .WithMany("Interactions")
                        .HasForeignKey("LeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("Lead", b =>
                {
                    b.Navigation("Interactions");
                });

            modelBuilder.Entity("SalesRepresentative", b =>
                {
                    b.Navigation("Leads");
                });
#pragma warning restore 612, 618
        }
    }
}
